// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>NewTest</b><br>
 * Generated     : <b>2020/06/02 11:53:12 am</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 10 amd64 10.0 <br>
 * 
 * @since  June 02, 2020
 * @author sanjeet.kumar
 */
public abstract class NewTestHelper extends RationalTestScript
{
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : Chrome
	 * 		.processName : chrome.exe
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : Chrome
	 * 		.processName : chrome.exe
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * Google: with default state.
	 *		.class : Html.HtmlDocument
	 * 		.title : Google
	 * 		.url : https://www.google.com/
	 */
	protected DocumentTestObject document_google() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_google"));
	}
	/**
	 * Google: with specific test context and state.
	 *		.class : Html.HtmlDocument
	 * 		.title : Google
	 * 		.url : https://www.google.com/
	 */
	protected DocumentTestObject document_google(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_google"), anchor, flags);
	}
	
	/**
	 * SoftwareTestingIndiaIBM: with default state.
	 *		.class : Html.HtmlDocument
	 * 		.title : Software testing - India | IBM
	 * 		.url : https://www.ibm.com/in-en/cloud/devops/software-testing?p1=Search&p4=43700052660 ...
	 */
	protected DocumentTestObject document_softwareTestingIndiaI() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_softwareTestingIndiaI"));
	}
	/**
	 * SoftwareTestingIndiaIBM: with specific test context and state.
	 *		.class : Html.HtmlDocument
	 * 		.title : Software testing - India | IBM
	 * 		.url : https://www.ibm.com/in-en/cloud/devops/software-testing?p1=Search&p4=43700052660 ...
	 */
	protected DocumentTestObject document_softwareTestingIndiaI(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_softwareTestingIndiaI"), anchor, flags);
	}
	
	/**
	 * vn1s0p1c0: with default state.
	 *		.text : IBM® DevOps Software Testing - Software Testing Tools\u200eAd·www.ibm.com/devops/test ...
	 * 		.id : vn1s0p1c0
	 * 		.href : https://www.ibm.com/in-en/cloud/devops/software-testing
	 * 		.class : Html.A
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_vn1s0p1c0() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_vn1s0p1c0"));
	}
	/**
	 * vn1s0p1c0: with specific test context and state.
	 *		.text : IBM® DevOps Software Testing - Software Testing Tools\u200eAd·www.ibm.com/devops/test ...
	 * 		.id : vn1s0p1c0
	 * 		.href : https://www.ibm.com/in-en/cloud/devops/software-testing
	 * 		.class : Html.A
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_vn1s0p1c0(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_vn1s0p1c0"), anchor, flags);
	}
	
	/**
	 * Search: with default state.
	 *		.id : 
	 * 		.type : text
	 * 		.class : Html.INPUT.text
	 * 		.title : Search
	 * 		.name : q
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_search() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_search"));
	}
	/**
	 * Search: with specific test context and state.
	 *		.id : 
	 * 		.type : text
	 * 		.class : Html.INPUT.text
	 * 		.title : Search
	 * 		.name : q
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_search(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_search"), anchor, flags);
	}
	
	

	protected NewTestHelper()
	{
		setScriptName("NewTest");
	}
	
}

